# Generated by Django 5.2.8 on 2026-01-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("anfang", models.DateTimeField()),
                ("ende", models.DateTimeField(blank=True, null=True)),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("teacher", "Teacher"),
                            ("student", "Student"),
                            ("both", "Both"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
