# Generated by Django 5.2.8 on 2026-01-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_lunch_post_comment_like"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frage", models.CharField(max_length=200, null=True)),
                ("antwort1", models.CharField(max_length=100, null=True)),
                ("antwort2", models.CharField(max_length=100, null=True)),
                ("antwort3", models.CharField(max_length=100, null=True)),
                ("antwort4", models.CharField(max_length=100, null=True)),
                ("richtigeantwort", models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
