# Generated by Django 5.2.8 on 2026-02-01 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_quiz_lesson"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz_Sammlung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("questions", models.JSONField()),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.lesson"
                    ),
                ),
            ],
        ),
    ]
