# Generated by Django 5.2.8 on 2026-02-03 13:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_quiz_versuch"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quiz_versuch",
            old_name="Ergebniss",
            new_name="ergebniss",
        ),
    ]
