# Generated by Django 5.2.8 on 2026-02-03 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0008_rename_ergebniss_quiz_versuch_ergebniss"),
    ]

    operations = [
        migrations.CreateModel(
            name="File_Lernmaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("file", models.FileField(upload_to="learnmaterials/")),
                ("hochgeladen_um", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lernmaterials",
                        to="myapp.lesson",
                    ),
                ),
            ],
        ),
    ]
