# Generated by Django 5.2.8 on 2026-02-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0009_file_lernmaterial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file_lernmaterial",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
