# Generated by Django 5.2.8 on 2026-02-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0010_file_lernmaterial_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titel", models.CharField(max_length=200)),
                ("kurz_text", models.TextField()),
                ("voll_text", models.TextField()),
                ("bild", models.ImageField(upload_to="news/")),
                ("kategorie", models.CharField(max_length=50)),
                ("erstellt_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
