# Generated by Django 5.2.8 on 2026-02-11 22:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0011_news"),
    ]

    operations = [
        migrations.AddField(
            model_name="lunch",
            name="date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
