# Generated by Django 5.2.8 on 2026-02-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0012_lunch_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lunch",
            name="date",
            field=models.DateField(),
        ),
    ]
