# Generated by Django 5.2.8 on 2026-02-16 20:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0014_kategorie_post_image_post_kategorie"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-submitted_at"]},
        ),
    ]
