# Generated by Django 5.2.8 on 2026-02-17 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0016_alter_like_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="kategorie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="myapp.kategorie",
            ),
        ),
    ]
