# Generated by Django 5.2.8 on 2026-02-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0017_alter_post_kategorie"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schoolbilder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bild", models.ImageField(upload_to="bilder/")),
                ("titel", models.CharField(max_length=100)),
            ],
        ),
    ]
