# Generated by Django 5.2.8 on 2026-02-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0018_schoolbilder"),
    ]

    operations = [
        migrations.CreateModel(
            name="Karriere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jobtitel", models.CharField(max_length=100)),
                ("jobbeschreibung", models.CharField(max_length=255)),
                ("erstellt_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
