# Generated by Django 5.2.8 on 2026-02-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0019_karriere"),
    ]

    operations = [
        migrations.AlterField(
            model_name="karriere",
            name="jobbeschreibung",
            field=models.CharField(max_length=1000),
        ),
    ]
