# Generated by Django 5.2.8 on 2026-02-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0020_alter_karriere_jobbeschreibung"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="teachers/"),
        ),
    ]
