# Generated by Django 5.2.8 on 2026-02-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0021_person_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="students/"),
        ),
    ]
